version: "3.8"

services:
  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    command: gunicorn server:app -b 127.0.0.1:5000 -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./data:/data:ro
    env_file:
      - .env

  client:
    build: ./seq2view-client
    restart: always
    tty: true  # Keep container running.
    volumes:
      - static-volume:/opt/client
    depends_on:
      - server

  web:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Attach static client code.
      - static-volume:/usr/share/nginx/html:ro
    ports:
      - 80:80
    depends_on:
      - server
      - client

volumes:
  static-volume:
