version: "3.8"

services:
  api-server:
    build: ./server
    restart: always
    command: gunicorn server:app -b :5050 -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./data:/data:ro
    env_file:
      - .env

  client:
    build: ./seq2view-client
    restart: always
    tty: true  # Keep container running.
    volumes:
      - static-volume:/opt/client
    depends_on:
      - api-server

  web:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Attach static client code.
      - static-volume:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "5000:5000"  # API server.
    depends_on:
      - api-server
      - client

volumes:
  static-volume:
